version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  gatewayapi:
    depends_on:
      - rabbitmq
    image: dtupayimage:latest
    container_name: dtupaytest
    labels:
      -test
    ports:
      - "8082:8082"
    restart: always
    logging: *default-logging
  reporting:
    depends_on:
      - gatewayapi
    image: reportingimage:latest
    container_name: reporttest
    labels:
      -test
    restart: always
    logging: *default-logging
  token:
    depends_on:
      - gatewayapi
    image: tokenmanagerimage:latest
    container_name: tokentest
    labels:
      -test
    restart: always
    logging: *default-logging
  user:
    depends_on:
      - gatewayapi
    image: usermanagerimage:latest
    container_name: usertest
    labels:
      -test
    restart: always
    logging: *default-logging
  payment:
    depends_on:
      - gatewayapi
    image: paymentmanagerimage:latest
    container_name: paymenttest
    labels:
      -test
    restart: always
    logging: *default-logging


